GET  http://localhost:5000/api/v1/race-list

###

GET  http://localhost:5000/api/v1/race-list/5e25a407464b9e033d837a0f

###

POST http://localhost:5000/api/v1/race-list
Content-Type: application/json

{
    "name": "Extraloppet 1km",
    "distance": 1,
    "date": "2020-03-01 12:00",
    "capacity": 30,
    "location": "Göteborg",
    "message": "Ett extralopp",
    "displayOption": "x"
}

###

DELETE http://localhost:5000/api/v1/race-list/5e5a8dfb795ed3518c8ecec7

###

PUT http://localhost:5000/api/v1/race-list/5e5a8dfb795ed3518c8ecec7
Content-Type: application/json

{
    "name": "Extraloppet 1km",
    "distance": 1,
    "date": "2020-03-01 16:00",
    "capacity": 20,
    "location": "Göteborg",
    "message": "Ett extralopp",
    "displayOption": "x"
}